version: "3.4"
services:
  zeek-capture:
    container_name: zeek-capture
    build: ./zeek/. 
    image: zeek-capture
    env_file: zeek_kibana.env
    network_mode: "host"
    cap_add: 
      - NET_ADMIN
    volumes:
      - type: bind
        source: ${PWD}/logs
        target: /opt/zeek/logs
        
  elastic:
    container_name: elasticsearch
    build: ./elasticsearch/.
    image: elasticsearch
    network_mode: "host"

  kibana:
   container_name: kibana
   build: ./kibana/.
   image: kibana
   network_mode: "host"
