## Subnets Config
## List of all desired subnets traffic generation is requested for in CIDR notation.
## If using mode 2, all subnets must be at least /16 to prevent docker errors
## If using mode 1, all subnets must be at least /24 to precent docker errors
#
## Note1: if using routable IP addresses you must configure a router to send traffic the machine hosting traffic generation for those subnets.
## Example: I want to emulate traffic from 98.120.0.0/16 and my traffic generation machine in 192.168.1.120;
# therefore, I need to configure a routing device to say 98.120.0.0/16 is via 129.168.1.120
#
## Note2: No spaces between subnets are allowed. Use # to separate subnets if required.
10.0.0.0/16
