version: "3.4"
services:
  zeek-capture:
    container_name: zeek-capture
    build: . 
    image: zeek-capture
    env_file: zeek_capture.env
    network_mode: "host"
    cap_add: 
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./logs
        target: /opt/zeek/logs
        bind:
          create_host_path: true
      - type: bind
        source: ./config/custom.zeek
        target: /opt/zeek/share/zeek/custom.zeek
        bind:
          create_host_path: true




